const ChannelEventsEnum = Object.freeze({
    ADDED_TO_NEW_CHANNEL: "ADDED_TO_NEW_CHANNEL",
    REMOVED_FROM_CHANNEL: "REMOVED_FROM_CHANNEL",
    CHANGE_CHANNEL_TYPE: "CHANGE_CHANNEL_TYPE",
    REMOVE_USER_FROM_CHANNEL: "REMOVE_USER_FROM_CHANNEL",
    ADDED_AS_MANAGER: "ADDED_AS_MANAGER",
    REMOVED_MANAGER_ROLE: "REMOVED_MANAGER_ROLE",
    ARCHIVE_CHANNEL: "ARCHIVE_CHANNEL",
    UNARCHIVE_CHANNEL: "UNARCHIVE_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
});

export default ChannelEventsEnum;
