const WorkspaceEventsEnum = Object.freeze({
    STORE_CHANNEL: "STORE_CHANNEL",
    WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
    INVITATION_PERMISSIONS_UPDATED: "INVITATION_PERMISSIONS_UPDATED",
    DEACTIVATE_USER_UPDATED: "DEACTIVATE_USER_UPDATED",
    ACCEPT_JOINING_REQUEST: "ACCEPT_JOINING_REQUEST",
    USER_ROLE_UPDATED: "USER_ROLE_UPDATED",
    USER_UPDATED: "USER_UPDATED",
    NEW_USER_JOIN_WORKSPACE: "NEW_USER_JOIN_WORKSPACE",
    NEW_USER_REQUEST_TO_JOIN_WORKSPACE: "NEW_USER_REQUEST_TO_JOIN_WORKSPACE",
});

export default WorkspaceEventsEnum;
