const ChannelEventsEnum = Object.freeze({
    //user notification events
    ADDED_TO_NEW_CHANNEL: "ADDED_TO_NEW_CHANNEL",
    REMOVED_FROM_CHANNEL: "REMOVED_FROM_CHANNEL",
    ADDED_AS_MANAGER: "ADDED_AS_MANAGER",
    REMOVED_MANAGER_ROLE: "REMOVED_MANAGER_ROLE",
    //Property update
    CHANNEL_UPDATED: "CHANNEL_UPDATED",
    //channel events
    CHANGE_CHANNEL_TYPE: "CHANGE_CHANNEL_TYPE",
    REMOVE_USER_FROM_CHANNEL: "REMOVE_USER_FROM_CHANNEL",
    ARCHIVE_CHANNEL: "ARCHIVE_CHANNEL",
    UNARCHIVE_CHANNEL: "UNARCHIVE_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
    ADD_MANAGERS: "ADD_MANAGERS",
    REMOVE_MANAGER: "REMOVE_MANAGER",
    ADD_USERS_TO_CHANNEL: "ADD_USERS_TO_CHANNEL",
    UPDATE_CHANNEL_PERMISSIONS: "UPDATE_CHANNEL_PERMISSIONS",
    NEW_USER_JOIN: "NEW_USER_JOIN",
    LEAVE: "LEAVE",
    //file events
    FILE_CREATED: "FILE_CREATED",
    FILE_DELETED: "FILE_DELETED",
    //Message events
    NEW_MESSAGE_CREATED: "NEW_MESSAGE_CREATED",
    MESSAGE_EDITED: "MESSAGE_EDITED",
    MESSAGE_DELETED: "MESSAGE_DELETED",
    REACTION_CREATED: "REACTION_CREATED",
    REACTION_DELETED: "REACTION_DELETED",
});

export default ChannelEventsEnum;
