const WorkspaceEventsEnum = Object.freeze({
    STORE_CHANNEL: "STORE_CHANNEL",
    WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
    INVITATION_PERMISSIONS_UPDATED: "INVITATION_PERMISSIONS_UPDATED",
    DEACTIVATE_USER_UPDATED: "DEACTIVATE_USER_UPDATED",
    ACCEPT_JOINING_REQUEST: "ACCEPT_JOINING_REQUEST",
    USER_ROLE_UPDATED: "USER_ROLE_UPDATED",
    USER_UPDATED: "USER_UPDATED",
    NEW_USER_JOIN_WORKSPACE: "NEW_USER_JOIN_WORKSPACE",
    NEW_USER_REQUEST_TO_JOIN_WORKSPACE: "NEW_USER_REQUEST_TO_JOIN_WORKSPACE",
    INVITATION_LINK_CREATED: "INVITATION_LINK_CREATED",
    INVITATION_LINK_UPDATED: "INVITATION_LINK_UPDATED",
    INVITATION_LINK_DELETED: "INVITATION_LINK_DELETED",
    INVITATION_TYPE_EMAIL_CREATED: "INVITATION_TYPE_EMAIL_CREATED",
    INVITATION_TYPE_EMAIL_UPDATED: "INVITATION_TYPE_EMAIL_UPDATED",
    INVITATION_TYPE_EMAIL_DELETED: "INVITATION_TYPE_EMAIL_DELETED",
    WORKSPACE_DELETED: "WORKSPACE_DELETED",
});

export default WorkspaceEventsEnum;
